import type { Career } from "./types";

export const CAREERS: Career[] = [
  // Medicine
  {
    id: "gp",
    name: "General Practitioner",
    category: "medicine",
    educationRequired: "postgrad",
    yearsToQualify: 7,
    startingSalary: 7000,
    maxSalary: 18000,
    happinessBonus: 6,
    stressLevel: 7,
    description: "Diagnose and treat patients in a clinic.",
  },
  {
    id: "surgeon",
    name: "Surgeon",
    category: "medicine",
    educationRequired: "postgrad",
    yearsToQualify: 12,
    startingSalary: 10000,
    maxSalary: 35000,
    happinessBonus: 5,
    stressLevel: 10,
    description: "Perform complex surgical procedures.",
  },
  {
    id: "nurse",
    name: "Nurse",
    category: "medicine",
    educationRequired: "degree",
    yearsToQualify: 3,
    startingSalary: 3500,
    maxSalary: 7000,
    happinessBonus: 7,
    stressLevel: 8,
    description: "Care for patients in hospitals and clinics.",
  },
  {
    id: "dentist",
    name: "Dentist",
    category: "medicine",
    educationRequired: "postgrad",
    yearsToQualify: 5,
    startingSalary: 6000,
    maxSalary: 20000,
    happinessBonus: 4,
    stressLevel: 5,
    description: "Provide dental care and treatment.",
  },
  {
    id: "pharmacist",
    name: "Pharmacist",
    category: "medicine",
    educationRequired: "degree",
    yearsToQualify: 4,
    startingSalary: 5000,
    maxSalary: 12000,
    happinessBonus: 5,
    stressLevel: 4,
    description: "Dispense medications and advise patients.",
  },
  {
    id: "psychologist",
    name: "Psychologist",
    category: "medicine",
    educationRequired: "postgrad",
    yearsToQualify: 6,
    startingSalary: 5500,
    maxSalary: 14000,
    happinessBonus: 7,
    stressLevel: 6,
    description: "Provide mental health therapy and counseling.",
  },
  {
    id: "veterinarian",
    name: "Veterinarian",
    category: "medicine",
    educationRequired: "postgrad",
    yearsToQualify: 5,
    startingSalary: 5000,
    maxSalary: 13000,
    happinessBonus: 8,
    stressLevel: 5,
    description: "Treat animals and promote animal welfare.",
  },
  {
    id: "paramedic",
    name: "Paramedic",
    category: "medicine",
    educationRequired: "vocational",
    yearsToQualify: 2,
    startingSalary: 3000,
    maxSalary: 6000,
    happinessBonus: 6,
    stressLevel: 9,
    description: "Provide emergency medical care on-site.",
  },

  // Law
  {
    id: "lawyer",
    name: "Lawyer",
    category: "law",
    educationRequired: "postgrad",
    yearsToQualify: 5,
    startingSalary: 6000,
    maxSalary: 30000,
    happinessBonus: 3,
    stressLevel: 9,
    description: "Represent clients in legal matters.",
  },
  {
    id: "judge",
    name: "Judge",
    category: "law",
    educationRequired: "postgrad",
    yearsToQualify: 10,
    startingSalary: 8000,
    maxSalary: 20000,
    happinessBonus: 6,
    stressLevel: 7,
    description: "Preside over court cases and deliver verdicts.",
  },
  {
    id: "paralegal",
    name: "Paralegal",
    category: "law",
    educationRequired: "degree",
    yearsToQualify: 3,
    startingSalary: 3000,
    maxSalary: 7000,
    happinessBonus: 3,
    stressLevel: 6,
    description: "Assist lawyers with legal research and documentation.",
  },

  // Engineering
  {
    id: "software_eng",
    name: "Software Engineer",
    category: "tech",
    educationRequired: "degree",
    yearsToQualify: 4,
    startingSalary: 6000,
    maxSalary: 25000,
    happinessBonus: 5,
    stressLevel: 6,
    description: "Design and build software systems.",
  },
  {
    id: "data_scientist",
    name: "Data Scientist",
    category: "tech",
    educationRequired: "degree",
    yearsToQualify: 4,
    startingSalary: 6500,
    maxSalary: 22000,
    happinessBonus: 5,
    stressLevel: 5,
    description: "Analyze complex datasets to find insights.",
  },
  {
    id: "civil_eng",
    name: "Civil Engineer",
    category: "engineering",
    educationRequired: "degree",
    yearsToQualify: 4,
    startingSalary: 5000,
    maxSalary: 16000,
    happinessBonus: 4,
    stressLevel: 6,
    description: "Design infrastructure like bridges and roads.",
  },
  {
    id: "architect",
    name: "Architect",
    category: "engineering",
    educationRequired: "degree",
    yearsToQualify: 5,
    startingSalary: 5000,
    maxSalary: 18000,
    happinessBonus: 7,
    stressLevel: 6,
    description: "Design buildings and urban spaces.",
  },
  {
    id: "mech_eng",
    name: "Mechanical Engineer",
    category: "engineering",
    educationRequired: "degree",
    yearsToQualify: 4,
    startingSalary: 5500,
    maxSalary: 16000,
    happinessBonus: 4,
    stressLevel: 5,
    description: "Design and build mechanical systems.",
  },
  {
    id: "electrical_eng",
    name: "Electrical Engineer",
    category: "engineering",
    educationRequired: "degree",
    yearsToQualify: 4,
    startingSalary: 5500,
    maxSalary: 16000,
    happinessBonus: 4,
    stressLevel: 5,
    description: "Design electrical systems and components.",
  },
  {
    id: "ux_designer",
    name: "UX Designer",
    category: "tech",
    educationRequired: "degree",
    yearsToQualify: 3,
    startingSalary: 5000,
    maxSalary: 15000,
    happinessBonus: 7,
    stressLevel: 4,
    description: "Design user-friendly digital interfaces.",
  },

  // Business & Finance
  {
    id: "accountant",
    name: "Accountant",
    category: "business",
    educationRequired: "degree",
    yearsToQualify: 3,
    startingSalary: 4000,
    maxSalary: 14000,
    happinessBonus: 2,
    stressLevel: 5,
    description: "Manage financial records and taxation.",
  },
  {
    id: "investment_banker",
    name: "Investment Banker",
    category: "business",
    educationRequired: "degree",
    yearsToQualify: 4,
    startingSalary: 8000,
    maxSalary: 50000,
    happinessBonus: 1,
    stressLevel: 10,
    description: "Execute large financial transactions and deals.",
  },
  {
    id: "financial_advisor",
    name: "Financial Advisor",
    category: "business",
    educationRequired: "degree",
    yearsToQualify: 3,
    startingSalary: 4500,
    maxSalary: 18000,
    happinessBonus: 4,
    stressLevel: 5,
    description: "Help clients manage money and investments.",
  },
  {
    id: "marketing_manager",
    name: "Marketing Manager",
    category: "business",
    educationRequired: "degree",
    yearsToQualify: 3,
    startingSalary: 4500,
    maxSalary: 16000,
    happinessBonus: 5,
    stressLevel: 6,
    description: "Plan and execute marketing campaigns.",
  },
  {
    id: "hr_manager",
    name: "HR Manager",
    category: "business",
    educationRequired: "degree",
    yearsToQualify: 3,
    startingSalary: 4000,
    maxSalary: 12000,
    happinessBonus: 4,
    stressLevel: 5,
    description: "Manage employee relations and recruitment.",
  },
  {
    id: "entrepreneur",
    name: "Entrepreneur",
    category: "business",
    educationRequired: "none",
    yearsToQualify: 0,
    startingSalary: 0,
    maxSalary: 100000,
    happinessBonus: 8,
    stressLevel: 9,
    description: "Build your own business from the ground up.",
  },
  {
    id: "real_estate_agent",
    name: "Real Estate Agent",
    category: "business",
    educationRequired: "secondary",
    yearsToQualify: 1,
    startingSalary: 2500,
    maxSalary: 20000,
    happinessBonus: 5,
    stressLevel: 5,
    description: "Buy and sell properties for clients.",
  },

  // Education
  {
    id: "teacher",
    name: "Teacher",
    category: "education",
    educationRequired: "degree",
    yearsToQualify: 4,
    startingSalary: 3000,
    maxSalary: 7000,
    happinessBonus: 8,
    stressLevel: 6,
    description: "Educate children in schools.",
  },
  {
    id: "professor",
    name: "Professor",
    category: "education",
    educationRequired: "doctorate",
    yearsToQualify: 8,
    startingSalary: 5000,
    maxSalary: 14000,
    happinessBonus: 8,
    stressLevel: 5,
    description: "Teach and research at a university.",
  },
  {
    id: "school_principal",
    name: "School Principal",
    category: "education",
    educationRequired: "postgrad",
    yearsToQualify: 6,
    startingSalary: 6000,
    maxSalary: 12000,
    happinessBonus: 7,
    stressLevel: 7,
    description: "Lead and manage a school.",
  },

  // Arts & Media
  {
    id: "artist",
    name: "Artist",
    category: "arts",
    educationRequired: "none",
    yearsToQualify: 0,
    startingSalary: 1000,
    maxSalary: 50000,
    happinessBonus: 9,
    stressLevel: 4,
    description: "Create visual art and sell it.",
  },
  {
    id: "musician",
    name: "Musician",
    category: "arts",
    educationRequired: "none",
    yearsToQualify: 0,
    startingSalary: 800,
    maxSalary: 100000,
    happinessBonus: 9,
    stressLevel: 5,
    description: "Perform and record music.",
  },
  {
    id: "actor",
    name: "Actor",
    category: "arts",
    educationRequired: "none",
    yearsToQualify: 0,
    startingSalary: 1000,
    maxSalary: 80000,
    happinessBonus: 8,
    stressLevel: 6,
    description: "Perform in films, TV, and theatre.",
  },
  {
    id: "writer",
    name: "Writer",
    category: "arts",
    educationRequired: "none",
    yearsToQualify: 0,
    startingSalary: 500,
    maxSalary: 40000,
    happinessBonus: 9,
    stressLevel: 3,
    description: "Write books, scripts, and articles.",
  },
  {
    id: "journalist",
    name: "Journalist",
    category: "arts",
    educationRequired: "degree",
    yearsToQualify: 3,
    startingSalary: 3000,
    maxSalary: 10000,
    happinessBonus: 6,
    stressLevel: 7,
    description: "Report news and write articles.",
  },
  {
    id: "photographer",
    name: "Photographer",
    category: "arts",
    educationRequired: "vocational",
    yearsToQualify: 1,
    startingSalary: 2000,
    maxSalary: 15000,
    happinessBonus: 8,
    stressLevel: 3,
    description: "Capture photographs professionally.",
  },
  {
    id: "influencer",
    name: "Social Media Influencer",
    category: "arts",
    educationRequired: "none",
    yearsToQualify: 0,
    startingSalary: 500,
    maxSalary: 50000,
    happinessBonus: 7,
    stressLevel: 5,
    description: "Build an audience online and monetize.",
  },
  {
    id: "streamer",
    name: "Content Streamer",
    category: "arts",
    educationRequired: "none",
    yearsToQualify: 0,
    startingSalary: 300,
    maxSalary: 30000,
    happinessBonus: 8,
    stressLevel: 4,
    description: "Stream games and content online.",
  },

  // Sports
  {
    id: "footballer",
    name: "Professional Footballer",
    category: "sports",
    educationRequired: "none",
    yearsToQualify: 0,
    startingSalary: 3000,
    maxSalary: 500000,
    happinessBonus: 9,
    stressLevel: 7,
    description: "Play professional football.",
  },
  {
    id: "cricketer",
    name: "Professional Cricketer",
    category: "sports",
    educationRequired: "none",
    yearsToQualify: 0,
    startingSalary: 2000,
    maxSalary: 200000,
    happinessBonus: 8,
    stressLevel: 6,
    description: "Play professional cricket.",
  },
  {
    id: "tennis_player",
    name: "Tennis Player",
    category: "sports",
    educationRequired: "none",
    yearsToQualify: 0,
    startingSalary: 1500,
    maxSalary: 300000,
    happinessBonus: 8,
    stressLevel: 7,
    description: "Compete in professional tennis.",
  },
  {
    id: "fitness_trainer",
    name: "Fitness Trainer",
    category: "sports",
    educationRequired: "vocational",
    yearsToQualify: 1,
    startingSalary: 2500,
    maxSalary: 8000,
    happinessBonus: 8,
    stressLevel: 3,
    description: "Train clients to improve fitness.",
  },

  // Military & Public Safety
  {
    id: "soldier",
    name: "Soldier",
    category: "military",
    educationRequired: "secondary",
    yearsToQualify: 1,
    startingSalary: 2500,
    maxSalary: 8000,
    happinessBonus: 4,
    stressLevel: 9,
    description: "Serve in the armed forces.",
  },
  {
    id: "police_officer",
    name: "Police Officer",
    category: "military",
    educationRequired: "secondary",
    yearsToQualify: 1,
    startingSalary: 3000,
    maxSalary: 8000,
    happinessBonus: 5,
    stressLevel: 8,
    description: "Maintain law and order.",
  },
  {
    id: "firefighter",
    name: "Firefighter",
    category: "military",
    educationRequired: "secondary",
    yearsToQualify: 1,
    startingSalary: 3000,
    maxSalary: 7000,
    happinessBonus: 7,
    stressLevel: 9,
    description: "Respond to fires and emergencies.",
  },
  {
    id: "pilot",
    name: "Pilot",
    category: "military",
    educationRequired: "vocational",
    yearsToQualify: 4,
    startingSalary: 7000,
    maxSalary: 20000,
    happinessBonus: 8,
    stressLevel: 7,
    description: "Fly commercial or private aircraft.",
  },

  // Science
  {
    id: "biologist",
    name: "Biologist",
    category: "science",
    educationRequired: "degree",
    yearsToQualify: 4,
    startingSalary: 4000,
    maxSalary: 12000,
    happinessBonus: 7,
    stressLevel: 4,
    description: "Study living organisms and ecosystems.",
  },
  {
    id: "physicist",
    name: "Physicist",
    category: "science",
    educationRequired: "doctorate",
    yearsToQualify: 7,
    startingSalary: 5000,
    maxSalary: 14000,
    happinessBonus: 7,
    stressLevel: 5,
    description: "Research the fundamental laws of nature.",
  },
  {
    id: "chemist",
    name: "Chemist",
    category: "science",
    educationRequired: "degree",
    yearsToQualify: 4,
    startingSalary: 4500,
    maxSalary: 13000,
    happinessBonus: 6,
    stressLevel: 4,
    description: "Research chemical compounds and reactions.",
  },
  {
    id: "economist",
    name: "Economist",
    category: "science",
    educationRequired: "postgrad",
    yearsToQualify: 5,
    startingSalary: 6000,
    maxSalary: 18000,
    happinessBonus: 5,
    stressLevel: 5,
    description: "Analyze economic trends and policy.",
  },

  // Trades
  {
    id: "electrician",
    name: "Electrician",
    category: "trades",
    educationRequired: "vocational",
    yearsToQualify: 2,
    startingSalary: 3500,
    maxSalary: 9000,
    happinessBonus: 5,
    stressLevel: 5,
    description: "Install and maintain electrical systems.",
  },
  {
    id: "plumber",
    name: "Plumber",
    category: "trades",
    educationRequired: "vocational",
    yearsToQualify: 2,
    startingSalary: 3500,
    maxSalary: 9000,
    happinessBonus: 4,
    stressLevel: 4,
    description: "Install and fix plumbing systems.",
  },
  {
    id: "carpenter",
    name: "Carpenter",
    category: "trades",
    educationRequired: "vocational",
    yearsToQualify: 2,
    startingSalary: 3000,
    maxSalary: 8000,
    happinessBonus: 6,
    stressLevel: 4,
    description: "Build and repair wooden structures.",
  },
  {
    id: "mechanic",
    name: "Mechanic",
    category: "trades",
    educationRequired: "vocational",
    yearsToQualify: 2,
    startingSalary: 3000,
    maxSalary: 7000,
    happinessBonus: 5,
    stressLevel: 4,
    description: "Repair and maintain vehicles.",
  },
  {
    id: "chef",
    name: "Chef",
    category: "trades",
    educationRequired: "vocational",
    yearsToQualify: 2,
    startingSalary: 2500,
    maxSalary: 15000,
    happinessBonus: 7,
    stressLevel: 8,
    description: "Cook and create dishes professionally.",
  },
  {
    id: "hairdresser",
    name: "Hairdresser",
    category: "trades",
    educationRequired: "vocational",
    yearsToQualify: 1,
    startingSalary: 2000,
    maxSalary: 6000,
    happinessBonus: 7,
    stressLevel: 3,
    description: "Cut, style, and colour hair.",
  },
  {
    id: "farmer",
    name: "Farmer",
    category: "trades",
    educationRequired: "none",
    yearsToQualify: 0,
    startingSalary: 2000,
    maxSalary: 8000,
    happinessBonus: 6,
    stressLevel: 7,
    description: "Grow crops and raise livestock.",
  },

  // Service
  {
    id: "truck_driver",
    name: "Truck Driver",
    category: "service",
    educationRequired: "secondary",
    yearsToQualify: 1,
    startingSalary: 2800,
    maxSalary: 6000,
    happinessBonus: 3,
    stressLevel: 5,
    description: "Transport goods across long distances.",
  },
  {
    id: "delivery_driver",
    name: "Delivery Driver",
    category: "service",
    educationRequired: "secondary",
    yearsToQualify: 0,
    startingSalary: 2000,
    maxSalary: 4000,
    happinessBonus: 3,
    stressLevel: 4,
    description: "Deliver packages to customers.",
  },
  {
    id: "security_guard",
    name: "Security Guard",
    category: "service",
    educationRequired: "secondary",
    yearsToQualify: 0,
    startingSalary: 1800,
    maxSalary: 4000,
    happinessBonus: 2,
    stressLevel: 5,
    description: "Protect premises and people.",
  },
  {
    id: "waiter",
    name: "Waiter",
    category: "service",
    educationRequired: "none",
    yearsToQualify: 0,
    startingSalary: 1500,
    maxSalary: 4000,
    happinessBonus: 4,
    stressLevel: 5,
    description: "Serve food and drinks in a restaurant.",
  },
  {
    id: "barista",
    name: "Barista",
    category: "service",
    educationRequired: "none",
    yearsToQualify: 0,
    startingSalary: 1500,
    maxSalary: 3500,
    happinessBonus: 5,
    stressLevel: 3,
    description: "Prepare and serve coffee drinks.",
  },
  {
    id: "cleaner",
    name: "Cleaner",
    category: "service",
    educationRequired: "none",
    yearsToQualify: 0,
    startingSalary: 1200,
    maxSalary: 3000,
    happinessBonus: 2,
    stressLevel: 3,
    description: "Clean homes, offices, and public spaces.",
  },
  {
    id: "shop_owner",
    name: "Shop Owner",
    category: "service",
    educationRequired: "secondary",
    yearsToQualify: 0,
    startingSalary: 2000,
    maxSalary: 20000,
    happinessBonus: 6,
    stressLevel: 7,
    description: "Own and run a retail shop.",
  },

  // Politics
  {
    id: "politician",
    name: "Politician",
    category: "politics",
    educationRequired: "degree",
    yearsToQualify: 4,
    startingSalary: 5000,
    maxSalary: 20000,
    happinessBonus: 5,
    stressLevel: 9,
    description: "Serve in government and make policy.",
  },
  {
    id: "civil_servant",
    name: "Civil Servant",
    category: "politics",
    educationRequired: "degree",
    yearsToQualify: 3,
    startingSalary: 3500,
    maxSalary: 10000,
    happinessBonus: 4,
    stressLevel: 5,
    description: "Work for the government bureaucracy.",
  },
];

export const CAREER_CATEGORIES = [
  { id: "medicine", label: "Medicine & Health", color: "text-red-400" },
  { id: "law", label: "Law", color: "text-yellow-400" },
  { id: "tech", label: "Technology", color: "text-blue-400" },
  { id: "engineering", label: "Engineering", color: "text-cyan-400" },
  { id: "business", label: "Business & Finance", color: "text-green-400" },
  { id: "education", label: "Education", color: "text-orange-400" },
  { id: "arts", label: "Arts & Media", color: "text-pink-400" },
  { id: "sports", label: "Sports", color: "text-lime-400" },
  { id: "military", label: "Military & Safety", color: "text-slate-300" },
  { id: "science", label: "Science", color: "text-violet-400" },
  { id: "trades", label: "Trades", color: "text-amber-400" },
  { id: "service", label: "Service", color: "text-teal-400" },
  { id: "politics", label: "Politics", color: "text-purple-400" },
];
