/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : string,
  'doctorId' : bigint,
  'paymentStatus' : string,
  'paymentMethod' : string,
  'patientId' : bigint,
  'date' : string,
  'hospitalId' : bigint,
  'hospitalAddress' : string,
  'patientName' : string,
  'hospitalName' : string,
  'doctorName' : string,
  'slotNumber' : string,
}
export interface Doctor {
  'id' : bigint,
  'name' : string,
  'available' : boolean,
  'specialty' : string,
  'hospitalId' : bigint,
  'charge' : bigint,
  'phone' : string,
}
export interface Hospital {
  'id' : bigint,
  'latitude' : number,
  'name' : string,
  'longitude' : number,
  'address' : string,
  'facilities' : Array<string>,
  'rating' : number,
  'phone' : string,
  'doctorIds' : Array<bigint>,
}
export interface Patient { 'id' : bigint, 'name' : string, 'phone' : string }
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'userType' : string,
  'name' : string,
  'entityId' : [] | [bigint],
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDoctorToHospital' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'completeBooking' : ActorMethod<[bigint], undefined>,
  'confirmBookingPayment' : ActorMethod<[bigint], undefined>,
  'createBooking' : ActorMethod<
    [bigint, bigint, bigint, string, string],
    bigint
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createDoctor' : ActorMethod<
    [string, string, string, bigint, bigint, boolean],
    bigint
  >,
  'createHospital' : ActorMethod<
    [string, string, string, number, number, number, Array<string>],
    bigint
  >,
  'createPatient' : ActorMethod<[string, string], bigint>,
  'createPaymentIntent' : ActorMethod<[bigint, string, bigint], string>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllDoctors' : ActorMethod<[], Array<Doctor>>,
  'getAllHospitals' : ActorMethod<[], Array<Hospital>>,
  'getBookingById' : ActorMethod<[bigint], [] | [Booking]>,
  'getBookingsByDoctor' : ActorMethod<[bigint], Array<Booking>>,
  'getBookingsByDoctorAndDate' : ActorMethod<[bigint, string], Array<Booking>>,
  'getBookingsByHospital' : ActorMethod<[bigint], Array<Booking>>,
  'getBookingsByPatient' : ActorMethod<[bigint], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDoctorById' : ActorMethod<[bigint], [] | [Doctor]>,
  'getDoctorByPhone' : ActorMethod<[string], [] | [Doctor]>,
  'getDoctorsByHospital' : ActorMethod<[bigint], Array<Doctor>>,
  'getHospitalById' : ActorMethod<[bigint], [] | [Hospital]>,
  'getHospitalByPhone' : ActorMethod<[string], [] | [Hospital]>,
  'getPatientById' : ActorMethod<[bigint], [] | [Patient]>,
  'getPatientByPhone' : ActorMethod<[string], [] | [Patient]>,
  'getSeedData' : ActorMethod<[], [Array<Hospital>, Array<Doctor>]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchDoctorsByNameOrSpecialty' : ActorMethod<[string], Array<Doctor>>,
  'seedData' : ActorMethod<[], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateDoctorProfile' : ActorMethod<
    [bigint, string, string, string, bigint, bigint, boolean],
    undefined
  >,
  'updateHospitalProfile' : ActorMethod<
    [bigint, string, string, string, number, number, number, Array<string>],
    undefined
  >,
  'updatePatientName' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];