/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'doctorId' : IDL.Nat,
  'paymentStatus' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'patientId' : IDL.Nat,
  'date' : IDL.Text,
  'hospitalId' : IDL.Nat,
  'hospitalAddress' : IDL.Text,
  'patientName' : IDL.Text,
  'hospitalName' : IDL.Text,
  'doctorName' : IDL.Text,
  'slotNumber' : IDL.Text,
});
export const Doctor = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'available' : IDL.Bool,
  'specialty' : IDL.Text,
  'hospitalId' : IDL.Nat,
  'charge' : IDL.Nat,
  'phone' : IDL.Text,
});
export const Hospital = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Float64,
  'name' : IDL.Text,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
  'facilities' : IDL.Vec(IDL.Text),
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
  'doctorIds' : IDL.Vec(IDL.Nat),
});
export const UserProfile = IDL.Record({
  'userType' : IDL.Text,
  'name' : IDL.Text,
  'entityId' : IDL.Opt(IDL.Nat),
  'phone' : IDL.Text,
});
export const Patient = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDoctorToHospital' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'completeBooking' : IDL.Func([IDL.Nat], [], []),
  'confirmBookingPayment' : IDL.Func([IDL.Nat], [], []),
  'createBooking' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createDoctor' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'createHospital' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'createPatient' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createPaymentIntent' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getAllHospitals' : IDL.Func([], [IDL.Vec(Hospital)], ['query']),
  'getBookingById' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
  'getBookingsByDoctor' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
  'getBookingsByDoctorAndDate' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getBookingsByHospital' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
  'getBookingsByPatient' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDoctorById' : IDL.Func([IDL.Nat], [IDL.Opt(Doctor)], ['query']),
  'getDoctorByPhone' : IDL.Func([IDL.Text], [IDL.Opt(Doctor)], ['query']),
  'getDoctorsByHospital' : IDL.Func([IDL.Nat], [IDL.Vec(Doctor)], ['query']),
  'getHospitalById' : IDL.Func([IDL.Nat], [IDL.Opt(Hospital)], ['query']),
  'getHospitalByPhone' : IDL.Func([IDL.Text], [IDL.Opt(Hospital)], ['query']),
  'getPatientById' : IDL.Func([IDL.Nat], [IDL.Opt(Patient)], ['query']),
  'getPatientByPhone' : IDL.Func([IDL.Text], [IDL.Opt(Patient)], ['query']),
  'getSeedData' : IDL.Func([], [IDL.Vec(Hospital), IDL.Vec(Doctor)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchDoctorsByNameOrSpecialty' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Doctor)],
      ['query'],
    ),
  'seedData' : IDL.Func([], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateDoctorProfile' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'updateHospitalProfile' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'updatePatientName' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'doctorId' : IDL.Nat,
    'paymentStatus' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'patientId' : IDL.Nat,
    'date' : IDL.Text,
    'hospitalId' : IDL.Nat,
    'hospitalAddress' : IDL.Text,
    'patientName' : IDL.Text,
    'hospitalName' : IDL.Text,
    'doctorName' : IDL.Text,
    'slotNumber' : IDL.Text,
  });
  const Doctor = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'available' : IDL.Bool,
    'specialty' : IDL.Text,
    'hospitalId' : IDL.Nat,
    'charge' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const Hospital = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Float64,
    'name' : IDL.Text,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
    'facilities' : IDL.Vec(IDL.Text),
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
    'doctorIds' : IDL.Vec(IDL.Nat),
  });
  const UserProfile = IDL.Record({
    'userType' : IDL.Text,
    'name' : IDL.Text,
    'entityId' : IDL.Opt(IDL.Nat),
    'phone' : IDL.Text,
  });
  const Patient = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDoctorToHospital' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'completeBooking' : IDL.Func([IDL.Nat], [], []),
    'confirmBookingPayment' : IDL.Func([IDL.Nat], [], []),
    'createBooking' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createDoctor' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'createHospital' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'createPatient' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createPaymentIntent' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getAllHospitals' : IDL.Func([], [IDL.Vec(Hospital)], ['query']),
    'getBookingById' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
    'getBookingsByDoctor' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
    'getBookingsByDoctorAndDate' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getBookingsByHospital' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getBookingsByPatient' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDoctorById' : IDL.Func([IDL.Nat], [IDL.Opt(Doctor)], ['query']),
    'getDoctorByPhone' : IDL.Func([IDL.Text], [IDL.Opt(Doctor)], ['query']),
    'getDoctorsByHospital' : IDL.Func([IDL.Nat], [IDL.Vec(Doctor)], ['query']),
    'getHospitalById' : IDL.Func([IDL.Nat], [IDL.Opt(Hospital)], ['query']),
    'getHospitalByPhone' : IDL.Func([IDL.Text], [IDL.Opt(Hospital)], ['query']),
    'getPatientById' : IDL.Func([IDL.Nat], [IDL.Opt(Patient)], ['query']),
    'getPatientByPhone' : IDL.Func([IDL.Text], [IDL.Opt(Patient)], ['query']),
    'getSeedData' : IDL.Func(
        [],
        [IDL.Vec(Hospital), IDL.Vec(Doctor)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchDoctorsByNameOrSpecialty' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Doctor)],
        ['query'],
      ),
    'seedData' : IDL.Func([], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateDoctorProfile' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'updateHospitalProfile' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'updatePatientName' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };